package: org.robovm.pods.flurry.config
framework: FlurryConfig
include: [foundation, dispatch]
clang_args: ['-x', 'objective-c']
headers: 
    - FConfig.h
enums:

classes:
    FConfig:
        methods:
            '-getStringForKey:withDefault:':
                name: getString
            '-getBoolForKey:withDefault:':
                name: getBool
            '-getNumberForKey:withDefault:':
                name: getNumber
            '-registerObserver:withExecutionQueue:':
                name: registerObserver
                parameters:
                    0:
                        type: FConfigObserver

protocols:
    FConfigObserver: {}
functions:
    # Make sure we don't miss any functions if new ones are introduced in a later version
    (.*):
        class: __FixMe
        name: 'Function_#{g[0]}'

values:

    # Make sure we don't miss any values if new ones are introduced in a later version
    (.*):
        class: __FixMe
        name: 'Value_#{g[0]}'

constants:
    # Make sure we don't miss any constants if new ones are introduced in a later version
    (.*):
        class: __FixMe
        name: 'Constant__#{g[0]}'
